title: Qianli Zhou
description: Academic homepage of Qianli Zhou, Northwestern Polytechnical University
show_downloads: false
theme: jekyll-theme-hacker
baseurl: ""
profile_image: "/assets/images/ZQL.jpg"
